export const links = {
  github: 'https://github.com/skmc03',
  linkedin: 'https://www.linkedin.com/in/moinuddin-chisty',
  email: 'mailto:moinuddinchistyshaik@gmail.com',
  resume: '/Moinuddin-Chisty-Shaik-Resume.pdf',
};

export const projects = [
  {
    title: 'StockFlow',
    type: 'Full Stack / SaaS',
    category: 'Web',
    accent: 'mint',
    description: 'AI-oriented inventory management that centralizes products, stock levels and operational workflows.',
    stack: ['Python', 'Flask', 'React', 'MySQL', 'REST APIs'],
    features: ['Authentication', 'Inventory CRUD', 'Stock tracking', 'Deployed frontend + backend'],
    destination: 'https://stockflow-mvp-chi.vercel.app/',
    destinationLabel: 'Open live product',
  },
  {
    title: 'Flask E-Commerce',
    type: 'Full Stack Platform',
    category: 'Web',
    accent: 'violet',
    description: 'A secure, database-driven e-commerce experience with customer and admin workflows.',
    stack: ['Python', 'Flask', 'MySQL', 'Razorpay'],
    features: ['OTP flows', 'Product uploads', 'Cart & orders', 'Session security'],
    destination: 'https://github.com/skmc03/flask-ecommerce-project',
    destinationLabel: 'View GitHub repository',
  },
  {
    title: 'TechMap',
    type: 'Skill Graph & Learning Paths',
    category: 'Web',
    accent: 'blue',
    description: 'A full-stack platform that maps technology skill dependencies and helps learners find effective paths.',
    stack: ['Next.js', 'TypeScript', 'Neo4j', 'Tailwind CSS'],
    features: ['Graph visualisation', 'Shortest paths', 'Live search', 'REST APIs'],
    destination: 'https://techmap-iota.vercel.app/',
    destinationLabel: 'Open live product',
  },
  {
    title: 'Smart Water Quality',
    type: 'IoT / Final Year Project',
    category: 'IoT',
    accent: 'amber',
    description: 'An IoT monitoring system that captures water-quality sensor data and surfaces it through connected infrastructure.',
    stack: ['Arduino', 'ESP', 'Firebase', 'MQTT'],
    features: ['Sensor telemetry', 'Cloud monitoring', 'Connected dashboards'],
    destination: 'https://github.com/search?q=user%3Askmc03+water+quality&type=repositories',
    destinationLabel: 'Find the GitHub project',
  },
  {
    title: 'Breast Cancer Detection',
    type: 'Machine Learning',
    category: 'AI/ML',
    accent: 'rose',
    description: 'A breast cancer classification project developed during the Infosys Springboard internship.',
    stack: ['Python', 'scikit-learn', 'AdaBoost'],
    features: ['Classification', 'Data processing', 'Model development'],
    destination: 'https://github.com/skmc03/Atharvo-ML-Internship_BREAST-CANCER',
    destinationLabel: 'View GitHub repository',
  },
  {
    title: 'Water Level Monitoring',
    type: 'IoT / Internship',
    category: 'IoT',
    accent: 'amber',
    description: 'A connected water-level monitoring solution built during Samsung Innovation Campus.',
    stack: ['Arduino', 'NodeMCU', 'Sensors', 'Blynk'],
    features: ['Live sensor data', 'Microcontrollers', 'Cloud monitoring'],
    destination: 'https://github.com/skmc03/Water-level-monitoring-system',
    destinationLabel: 'View GitHub repository',
  },
  {
    title: 'Image Steganography',
    type: 'Python Project',
    category: 'AI/ML',
    accent: 'violet',
    description: 'A Python project for concealing information within digital images.',
    stack: ['Python', 'Image Processing'],
    features: ['Data hiding', 'Image processing'],
    destination: 'https://github.com/skmc03',
    destinationLabel: 'Explore GitHub',
  },
  {
    title: 'Weather Forecasting',
    type: 'React Application',
    category: 'Web',
    accent: 'blue',
    description: 'A responsive weather application built around API-driven forecast data.',
    stack: ['React', 'JavaScript', 'APIs'],
    features: ['Forecast interface', 'API integration', 'Responsive UI'],
    destination: 'https://github.com/skmc03',
    destinationLabel: 'Explore GitHub',
  },
];

export const skillGroups = [
  ['Programming', ['Python', 'JavaScript', 'TypeScript', 'C']],
  ['Web & Backend', ['React', 'Next.js', 'Flask', 'REST APIs', 'HTML/CSS', 'Authentication']],
  ['Data & AI/ML', ['MySQL', 'Neo4j', 'scikit-learn', 'AdaBoost', 'Pandas', 'NumPy']],
  ['IoT & Embedded', ['Arduino', 'ESP32', 'Firebase', 'MQTT', 'Node-RED', 'Verilog HDL']],
  ['Tools', ['Git', 'GitHub', 'VS Code', 'Postman', 'Tableau', 'MATLAB']],
];

export const certificates = [
  { title: 'Python Full Stack Development', issuer: 'Codegnan IT Solutions', href: 'https://github.com/search?q=user%3Askmc03+Codegnan&type=code' },
  { title: 'Samsung Innovation Campus', issuer: 'Research Internship', href: 'https://github.com/search?q=user%3Askmc03+Samsung&type=code' },
  { title: 'Infosys Springboard', issuer: 'Machine Learning Internship', href: 'https://github.com/search?q=user%3Askmc03+Infosys&type=code' },
  { title: 'GATE 2025 - DA', issuer: 'Qualified', href: 'https://github.com/search?q=user%3Askmc03+GATE&type=code' },
  { title: 'HackerRank SQL', issuer: 'Intermediate', href: 'https://github.com/search?q=user%3Askmc03+HackerRank&type=code' },
];
